#include <exception>
#include <solution.hpp>

int main() {
  Solution s;
  s.Test();
}